### ISSUE TITLE
gtz需下rbin的旧版压缩数据在aws北京区的机器上解压失败，报错Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zhaolx01** [Genetalks/gtz#26]
aws北京区机器型号：c5.large
旧版压缩数据：ERR1288730.fastq.gz.gtz
解压失败日志：
```
ubuntu@ip-10-0-2-199:~/data/user1/data/data$ gtz -d ERR1288730.fastq.gz.gtz -z
Powered by GTXLab of Genetalks. (built in PROFESSIONAL-2.1.4-V-2020-06-30 01:41:41 )
Decompressor initializing ... 
(1/1) ERR1288730.fastq.gz decompressing ...
Segmentation fault (core dumped)
```

**Comment by zxy1555847** [comment]
请问您怎么解决的？？我也遇到这个问题了，求帮助

**Comment by superligen** [comment]
看起来是很早期的版本，压缩对应的rbin数据您是否手头有备份？一般gtz设计的时候，考虑过大家未来的恢复需要，没有对解压施加限制。gtz的算法实现应该非常谨慎。如果segment fault，检查一下，命令行是否有错误，rbin文件是否有破损，gtz文件本身是否有破损。你是存档在对象存储里，还是vm的磁盘里？


作为前开发者，我们已经离开了公司，因为知识产权属于前公司，所以目前我们没有修改和调试的权利。


这些数据是否是十分重要的数据，因为如果要联系前公司，获得授权，帮助恢复调试之前的代码，会是一段非常不容易的操作。如果确实非常重要且没有办法找到任何替代数据。我们可以尝试帮助你，但务必确定非常重要。毕竟还得联系以前团队人员，大家只能用休息时间协助。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年4月15日(周二) 晚上10:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Genetalks/gtz] gtz需下rbin的旧版压缩数据在aws北京区的机器上解压失败，报错Segmentation fault (core dumped) (#26)


   
请问您怎么解决的？？我也遇到这个问题了，求帮助

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
  zxy1555847 left a comment (Genetalks/gtz#26)
 
请问您怎么解决的？？我也遇到这个问题了，求帮助

**Comment by zxy1555847** [comment]
您好，非常感谢您的回复。就是前一天还正常的用解压了一批文件，第二天再用就报错段错误了，哪怕是同一个gtz文件。命令
gtz -d -z 19526541_S0_L002_R1_001.fastq.gz.gtz
然后管理员说是环境冲突，我清空bashrc和新建一个用户重新安装这个gtz：https://github.com/Genetalks/gtz/archive/refs/tags/professional_v3.0.1.tar.gz，然后执行，还是一样的段错误。
这批数据目前还是比较不好公开，考虑到您不方便公开您的联系方式，请问是否方便您添加我的微信，我们沟通一下？？15606389357.非常感谢。

**Comment by superligen** [comment]
先确认一下，内存这些是否够？  找一台空机器试试？

**Comment by zxy1555847** [comment]
内存肯定是够的，

![Image](https://github.com/user-attachments/assets/b24549dd-2978-42c0-bd91-d2f393152191)
我们这个机器就是刚启用的新机器
